apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bftedkpae-python 
  janus-idp.io/tekton: bftedkpae-python
  backstage.io/kubernetes-id: bftedkpae-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bftedkpae-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml